
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
   end

    config.vm.define :masina_4 do |masina_4|
        masina_1.vm.network :private_network, ip: "10.0.0.14"
        masina_1.vm.hostname = "masina4"
        masina_1.vm.synced_folder "../data_4", "/vagrant_data"
    end

    config.vm.define :masina_5 do |masina_5|
        masina_2.vm.network :private_network, ip: "10.0.0.15"
        masina_2.vm.hostname = "masina5"
        masina_2.vm.synced_folder "../data_5", "/vagrant_data"
    end

   config.vm.provision "install_stuff", type: "shell",  inline: <<-SHELL
     apt-get update
	 apt-get -y install default-jre
	 apt-get -y install zip
   SHELL

end
