
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1536"
   end

    config.vm.define :masina_4 do |masina_4|
        masina_4.vm.network :private_network, ip: "10.0.0.14"
        masina_4.vm.hostname = "masina4"
        masina_4.vm.synced_folder "../data_4", "/vagrant_data"
    end

    config.vm.define :masina_5 do |masina_5|
        masina_5.vm.network :private_network, ip: "10.0.0.15"
        masina_5.vm.hostname = "masina5"
        masina_5.vm.synced_folder "../data_5", "/vagrant_data"
    end

     config.vm.define :masina_6 do |masina_6|
         masina_6.vm.network :private_network, ip: "10.0.0.16"
         masina_6.vm.hostname = "masina6"
         masina_6.vm.synced_folder "../data_6", "/vagrant_data"
     end

   config.vm.provision "install_stuff", type: "shell",  inline: <<-SHELL
     apt-get update
	 apt-get -y install default-jre
	 apt-get -y install zip
   SHELL

   config.vm.provision "install_elastic_search", type: "shell", after: "install_stuff", inline: <<-SHELL
         wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
         echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
         sudo apt-get update
         sudo apt-get install elasticsearch
         cp /vagrant_data/elasticsearch.yml /etc/elasticsearch/
         cp /vagrant_data/jvm.options /etc/elasticsearch/
         service elasticsearch restart
   SHELL

end
